import type { Notification } from "@/lib/types";

export const notifications: Notification[] = [
  {
    id: "notif_1",
    userId: "staff_1",
    type: "request_submitted",
    title: "New project request",
    body: "Sage Garden Design submitted a request for Full Website.",
    read: false,
    createdAt: "2026-08-09T13:10:00.000Z",
    href: "/dashboard/projects?request=req_1",
  },
  {
    id: "notif_2",
    userId: "staff_1",
    type: "new_note",
    title: "New note on Bellini Foods — Landing Page",
    body: "Marco Bellini posted a note about additional product photography.",
    read: true,
    createdAt: "2026-07-22T08:40:00.000Z",
    href: "/dashboard/projects/proj_3",
  },
  {
    id: "notif_3",
    userId: "staff_1",
    type: "payment_succeeded",
    title: "Payment received",
    body: "Haven Therapy Group paid the deposit invoice.",
    read: true,
    createdAt: "2026-06-21T08:05:00.000Z",
    href: "/dashboard/invoices?invoice=inv_3",
  },
  {
    id: "notif_4",
    userId: "client_2",
    type: "project_stage_changed",
    title: "Your project moved to Review",
    body: "Haven Therapy — Website is now in Review. Take a look and let us know what you think.",
    read: false,
    createdAt: "2026-08-08T11:00:00.000Z",
  },
  {
    id: "notif_5",
    userId: "client_3",
    type: "extra_charge_created",
    title: "New invoice: additional product photography page",
    body: "An extra invoice for $250 was added to your project.",
    read: false,
    createdAt: "2026-07-22T09:00:00.000Z",
  },
];
